name = "Wasp Client Pack"
author = "Nick"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e4ed1b2847b526feb32e3a2e8edf3ea5ce02a772ad5614d4577d0333e4f6ea0"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
